### ISSUE TITLE
Setting up CI

### ISSUE THREAD

**Issue by clarfonthey** [florence-social/mastodon-fork#1]
Right now, none of the CI from the original repo is carried over here. Ideally, we should look through what the other repo has and trim things down so that things are easier to self-host.

**Comment by clarfonthey** [comment]
Set up Circle CI for now, to just use the existing configuration. Will switch to something else once we decide on what to use.

**Comment by ghost** [comment]
Circle CI seems to be working ok.  Any reason we don't just stick with it?

**Comment by clarfonthey** [comment]
The issue is that Circle CI isn't open source or self-hosted.

**Comment by ghost** [comment]
@clarfon Ahh sorry I thought it was like Travis with both an open and closed version.

**Comment by clarfonthey** [comment]
I'm just going to close this and we can plan hosting our own infrastructure on mattermost or something
