### ISSUE TITLE
Document which Docker image/tags to use

### ISSUE THREAD

**Issue by agateblue** [florence-social/mastodon-fork#100]
According to https://github.com/florence-social/mastodon-fork/issues/34. there is an automated build for docker images, which is great :tada: 

However, the `docker-compose.yml` file still references upstream's image, and I cannot find any mention to the Docker hub namespace to use to switch to Florence. (it's https://hub.docker.com/r/florencesoc/mastodon-fork by the way)

I think Florence could use a link somewhere in the Readme, and an update in the compose file. And the cherry on the cake would be to have instructions  to switch from upstream to Florence when running Docker, as well as having the "upgrade notes" in the release notes, like upstream does:

```
**Non-Docker only:**

- Install dependencies: bundle install and yarn install

**Both Docker and non-Docker:**

- Run database migrations:
    - Non-Docker: RAILS_ENV=production bundle exec rails db:migrate
    - Docker: docker-compose run --rm web rails db:migrate
- Precompile the assets:
    - Non-Docker: RAILS_ENV=production bundle exec rails assets:precompile
    - Docker: The assets are already precompiled during the build step
- Restart all Mastodon processes
- Clear cache:
    - Non-Docker: RAILS_ENV=production bin/tootctl cache clear
    - Docker: docker-compose run --rm web bin/tootctl cache clear

```

I can probably contribute the upstream-to-florence guide, I plan to do the transition this week :)

**Comment by agateblue** [comment]
[It looks like](https://hub.docker.com/r/florencesoc/mastodon-fork/tags) there is only a `latest` tag available on the Docker Hub. I tend to prefer having tagged images (e.g `2.9.0-prerelease1`) to know what I'm exactly running, be able to rollbacke etc., but I understand if it's not easily feasible right now :)

**Comment by mal0ki** [comment]
Thank you for reporting this. And yeah, the 0.1.0 release obviously wasn't perfect, not was it intended to be. 

Upgrade notes is something we decided to shift to a later release, for various reasons. But we need to double check that it's part of the release check-list

Docker set up will definitely be improved for later releases, so thank you for this input (hard to make this sentence sound genuine, but it is, and I'm groggy so words are hard).

**Comment by agateblue** [comment]
> Docker set up will definitely be improved for later releases, so thank you for this input (hard to make this sentence sound genuine, but it is, and I'm groggy so words are hard).

I know it's genuine ;), I'll share updates/documentiotn about the switch here!

**Comment by agateblue** [comment]
So, since I've found a workaround for #101, I can now share the complete instructions. Execute the following steps in the directory where your `docker-compose.yml` file is located:

- Pull Florence docker image: `docker pull florencesoc/mastodon-fork:latest`
- [optional] For a completely safe migration and no dataloss in case of rollback, stop the services with `docker-compose stop`
- [optional] Launch only the database container for backup with `docker-compose up -d db`
- [optional] Do a database backup with 
```
docker-compose exec db pg_dumpall -c -U postgres > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
```
- In your `docker-compose.yml`, ensure the `image:` used for the `web`, `streaming` and `sidekiq` services is `image: florencesoc/mastodon-fork:latest`
- [optional] Apply the workaround described in https://github.com/florence-social/mastodon-fork/issues/101#issuecomment-503203082 if you want to customize your toot/bio max length (if the issue isn't resolved)
- Clear the cache with `docker-compose run --rm web bin/tootctl cache clear`
- Restart the services with `docker-compose up -d`

Congrats, you are now running on Florence :tada:

**Comment by clarfonthey** [comment]
We actually didn't wait for the docker image to build before announcing the release, because the builds on hub.docker.com take around 5 hours each to build and… I don't know how to even begin to debug that. The plan for tags is that the current release will be described by:

* `latest`
* `pre-release-latest`
* `pre-release-0-latest`
* `pre-release-0.1-latest`
* `pre-release-0.1.0`
* `v0.0.1.0`
* `v0.0.1-latest`
* `v0.0-latest`
* `v0-latest`
* `2018-06-18`

It's just that setting up the tags to actually work is… something I need to figure out.

**Comment by agateblue** [comment]
Sounds good @clarfon, I have some experience with optimizing docker builds and CI/CD, so maybe I can help with that. I'll continue the discussion on Mattermost :)

As for the current issue, since the official documentation is still in the pipes, maybe we can close it (the instructions are documented here and can be included in the docs when it's up). I don't want to clutter the issue tracker with semi-resolved issues, but of course if you prefer to keep it open, that's fine by me!

**Comment by clarfonthey** [comment]
Sounds good to me!
