### ISSUE TITLE
Max toot and bio length settings are not saved in the admin UI

### ISSUE THREAD

**Issue by agateblue** [florence-social/mastodon-fork#101]
I've done the switch to Florence from stock Mastodon this afternoon, under Docker. I was on Mastodon 2.9.0 and I switched to Florence [v0.0.1.0](https://github.com/florence-social/mastodon-fork/releases/tag/v0.0.1.0), using the Docker image `florencesoc/mastodon-fork:latest`.

(The switch itself went well and my instance is now up and running under Florence, so congrats to everyone involved :heart:)

I have an issue when trying to update the max bio/toot length at `/admin/settings/edit` though. Basically, the options are displayed properly, but changing and saving the values doesn't work: the form is saved, but the value are resetted to their default, 500 characters.

# Steps to reproduce

1. Visit `/admin/settings/edit`
2. Update the max character count for bio/toot
3. Click save

A video reproducing the issue can be found [here](https://mastodon.eliotberriot.com/system/media_attachments/files/000/406/662/original/193d72ca0f582eb2.mp4?1560864489).

# Expected result

The updated values are saved properly.

# Actual result

The form saves without error, but the values arent't updated.

# Additional context

- I've tried with different values (higher or lower than the default), with no success.
- Saving other settings (e.g server name) works as intended
- I've inspected the POST request triggered when submitting the form, and the updated values for both fields are present and correct in the payload, so I suspect a server-side issue.
- I'm running Docker, and displaying the admin under Firefox 67, if that matters

**Comment by agateblue** [comment]
This is what I have in my SQL `settings` table:

```sql

SELECT var FROM settings ORDER BY var ASC;
                var                 
------------------------------------
 activity_api_enabled
 advanced_layout
 advanced_layout
 aggregate_reblogs
 auto_play_gif
 boost_modal
 bootstrap_timeline_accounts
 closed_registrations_message
 custom_css
 default_language
 default_privacy
 default_privacy
 default_sensitive
 delete_modal
 display_media
 expand_spoilers
 hero
 hide_network
 interactions
 interactions
 mascot
 min_invite_role
 noindex
 notification_emails
 notification_emails
 open_deletion
 open_registrations
 peers_api_enabled
 preview_sensitive_media
 profile_directory
 reduce_motion
 registrations_mode
 show_known_fediverse_at_about_page
 show_staff_badge
 site_contact_email
 site_contact_username
 site_description
 site_extended_description
 site_short_description
 site_terms
 site_title
 system_font_ui
 theme
 theme
 thumbnail
 timeline_preview
 unfollow_modal
(47 rows)
```

I see no track of `max_toot_chars` and `max_bio_chars`, which are apparently the names used for the corresponding options from #32 and #49.

**Comment by agateblue** [comment]
I didnt' find the root cause of the issue, but I have a workaround that involves settings the value directly in the database.

Open a database shell with `docker-compose exec db  psql -U postgres` then execute the following queries:

```sql

INSERT INTO settings (var, value, created_at, updated_at) VALUES ('max_bio_chars', E'--- 66666\n...', NOW(), NOW());
INSERT INTO settings (var, value, created_at, updated_at) VALUES ('max_toot_chars', E'--- 66666\n...', NOW(), NOW());
```
(Replace `66666` with your desired maximum)

Then clear the cache with `docker-compose run --rm web bin/tootctl cache clear` :tada:

**Comment by clarfonthey** [comment]
We should probably add tests for both of these once we get a fix out.

**Comment by clarfonthey** [comment]
Oh, it seems that there isn't actually a test for any of the admin settings. I just failed to merge things correctly. Uploading a fix.
