### ISSUE TITLE
Provide documentation for manually IP-blocking Gab's official instance server

### ISSUE THREAD

**Issue by jhaye** [florence-social/mastodon-fork#121]
As discussed in #108 we will create a documentation page of how to alter the firewall of a server manually to block Gab's servers on an IP basis, so those that don't use Docker can also protect themselves.

**Comment by mal0ki** [comment]
As discussed elsewhere, and mentioned in the now closed PR. This isn't going to work the way we'd like it to, and will be false advertising when it comes to what security it brings.
