### ISSUE TITLE
Advertise max toot / bio length in api/v1/instance

### ISSUE THREAD

**Issue by agateblue** [florence-social/mastodon-fork#128]
Whenever I try to write a toot with Tusky from an account using my Florence server, I'm still limited to 500 chars, despite the server being configured to allow longer toots.

I initially thought it was Tusky-related, but apparently, Tusky [do support configurable toot length](https://github.com/tuskyapp/Tusky/pull/571). After checking `/api/v1/instance` on [my server](https://mastodon.eliotberriot.com/api/v1/instance), I see no trace of the bio and toot length limit.

Do you think it could be possible to add those here, so Mastodon clients can reflect the configuration?

**Comment by mal0ki** [comment]
I'm incredibly biased (as I work with Tusky), but yes, I'd like us to add this.

**Comment by agateblue** [comment]
> I'm incredibly biased (as I work with Tusky), but yes, I'd like us to add this.

Let's say it could also benefit other Mastodon clients, then :D

**Comment by clarfonthey** [comment]
I believe that these are in the code so I'll check later to figure out why this is.
