### ISSUE TITLE
max_toot_chars value is string rather than integer

### ISSUE THREAD

**Issue by ghost** [florence-social/mastodon-fork#161]
Hi,

I migrated my account to a Florence instance but now I can't use my iOS client.
It seems that you modified the `max_toot_chars` value type. What's the purpose of this move?
Would you publish some docs to help app dev implement that?

Here is the issue I opened on the iOS client Toot! repo: https://github.com/DagAgren/toot/issues/340

Thanks in advance,

**Comment by 1011X** [comment]
Hey, thanks for submitting an issue.

The problem was that `max_toot_chars` was being passed as-is, and the way everything is stored in settings is as a string, so the necessary conversion to an integer wasn't being done. There will be a PR that fixes this soon.

**Comment by ghost** [comment]
Hi,

I’ve seen @1011X work has been merged in main branch, but can you tell me when a new release will be published?

Thanks again,

**Comment by clarfonthey** [comment]
@mthld we've been relatively swamped this week but I'll try and make sure a release gets done over the weekend.

**Comment by ghost** [comment]
@clarfon alright, many thanks!
