### ISSUE TITLE
Configurable character counts

### ISSUE THREAD

**Issue by clarfonthey** [florence-social/mastodon-fork#18]
This has been merged via #32.

Right now, this is going to remain open until translations are added to the admin UI and API.

**Comment by ghost** [comment]
I took the cyber.space version and made it a configurable option in the admin UI instead of an ENV variable which might also be nice
https://github.com/usbsnowcrash/mastodon/commit/c394862efb4722d53a86eaa03824ba2a37fbcab0

**Comment by clarfonthey** [comment]
@usbsnowcrash If you'd like to submit that as a PR please feel free!

**Comment by optikfluffel** [comment]
Just fiy: Pleroma also has this [in it's config file](https://git.pleroma.social/pleroma/pleroma/blob/develop/config/config.exs#L141).

**Comment by ghost** [comment]
@clarcharr Done!

**Comment by clarfonthey** [comment]
Closing this because I seem to have misunderstood; we do have this in the API in the same place that glitch.soc does. Translations can be tracked elsewhere.
