### ISSUE TITLE
Build developer team

### ISSUE THREAD

**Issue by clarfonthey** [florence-social/mastodon-fork#30]
Basically, we need to accumulate a list of trusted people who can accept PRs. This is on the to-do list for 0.1.

**Comment by ghost** [comment]
I'd love to help out, let me know.

**Comment by clarfonthey** [comment]
@usbsnowcrash I think at this point we've decided who we're going with on the team for now, although you're more than welcome to submit PRs and offer feedback on stuff. :)

I'm going to close this now. Once we've set things up post-1.0 we'll re-evaluate how we want to handle growing the team.
