### ISSUE TITLE
Setting up prebuilt Docker images

### ISSUE THREAD

**Issue by clarfonthey** [florence-social/mastodon-fork#34]
Will have to look up what this entails.

**Comment by 1011X** [comment]
Mainline Mastodon says it has support for Docker, so it seems like it'd just be a matter of building the image and including them in the GitHub releases.

This might be a good starting point for figuring out how to automate at least part of the process:
[Docker: Set up Automated builds](https://docs.docker.com/docker-hub/builds/)

**Comment by clarfonthey** [comment]
We're now set up at florencesoc/mastodon-fork.
