### ISSUE TITLE
Collapse Vote options under CW too

### ISSUE THREAD

**Issue by mal0ki** [florence-social/mastodon-fork#53]
For votes, collapse the options under a CW as well.

**Comment by clarfonthey** [comment]
Potentially will be merged as tootsuite/mastodon#10983

**Comment by mal0ki** [comment]
I think glitch alerady has this btw? (I noticed it on some instances running glitch)

**Comment by clarfonthey** [comment]
This was merged as part of 2.9.0, so, I'll close this now as fixed.
