### ISSUE TITLE
Set up release mailing list

### ISSUE THREAD

**Issue by clarfonthey** [florence-social/mastodon-fork#65]
We'd want this to email from a florencesoc.org address that people can filter for tags/etc.

**Comment by mal0ki** [comment]
Again https://write.as/florence-development/ will work for this purpose as well, as it has an email function. 

I feel like we can test that it actually works by all subscribing to it ourselves, and then send see if we receive the first post we eventually publish.

**Comment by clarfonthey** [comment]
Yup, that's correct. We can close this once we do that. :p

**Comment by clarfonthey** [comment]
Eh, don't care enough for testing. Going to close out the milestone. ;)
