### ISSUE TITLE
Create release checklist

### ISSUE THREAD

**Issue by clarfonthey** [florence-social/mastodon-fork#67]
Essentially, have a static document somewhere that lists what we need to do for every release. This should include:

* Picking a name for the release (not necessary until first non-pre-release)
* Writing a proper change log
* Creating a new entry in the RSS/Atom feed
* Sending out an email to the mailing list
* Posting to fediverse account
* Linking posts in the Mattermost server
* Making a GitHub release
* Building a docker image

**Comment by mal0ki** [comment]
Would continuing to use Milestones work for this? 

EDIT: My brain had entirely misread this thing.

**Comment by clarfonthey** [comment]
Basically, the idea is to write down what we're doing for the first release so that we remember to do it for every release.

**Comment by mal0ki** [comment]
WIP set up, some additional commentary added in the "Discussion" page of the same page. 

https://wiki.florencesoc.org/mw/Release_Checklist 

Anything missing from it?

**Comment by clarfonthey** [comment]
Only thing missing, I think, is documenting this checklist somewhere in the repo. I'll make a PR in the next day or so that does this.

**Comment by clarfonthey** [comment]
Eh, we don't need to document this in the repo-- I gave up on deciding where. I'll pin it in the mattermost channel for infra.
