### ISSUE TITLE
Make fediverse account for release updates

### ISSUE THREAD

**Issue by clarfonthey** [florence-social/mastodon-fork#68]
Right now, we're using `@forktogether@toot.cat` which works for now, although ideally we'd have an account which just lists new releases/upcoming features and nothing else, for people who like a low volume of updates.

**Comment by clarfonthey** [comment]
@mal0ki this is what `@florence-development@write.as` is for, right? So I can close this? 

[edit comment, by mal: added @ and inline-code to make it not an email ]

**Comment by mal0ki** [comment]
Yes, I was going to update that here later. :)
